export const tasksActions = {
  LOADING: "LOADING_TASKS",
  LOAD_ALL_TASKS: "LOAD_ALL_TASKS",
  ERROR: "LOADING_TASKS_ERROR",
  CREATE_TASK: "CREATE_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  DELETE_TASK: "DELETE_TASK",
  LOAD_TASK: "LOAD_TASK",
  TOGGLE_COMPLETION_TASK: "TOGGLE_COMPLETION_TASK",
  UPDATE_TAGS: "UPDATE_TAGS",
};
